### PR TITLE
chore(ci): optimize changelog generation

### PR DESCRIPTION
**Pull request by juliangieseke**
This should prevent Jenkins to create releases for _every single pr_. Only PRs that contain commits from type `fix`, `feat` or `perf` will trigger new releases.

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
Where is the ticket number for this?

**Comment by DanielMSchmidt** [comment]
@juliangieseke Could you link the Jira number, so it gets shown in our normal review flow?

**Comment by juliangieseke** [comment]
there is no jira number.

**Comment by DanielMSchmidt** [comment]
Could you create one for the next sprint, so that we don't miss out on these improvements?

**Pull request merged**
