### PR TITLE
chore(deps): update dependency husky to v1.0.0-rc.2

### PR DESCRIPTION
**Pull request by mesosphere-web**
This Pull Request updates dependency [husky](https://github.com/typicode/husky) from `v1.0.0-rc.1` to `v1.0.0-rc.2`

<details>
<summary>Release Notes</summary>

### [`v1.0.0-rc.2`](https://github.com/typicode/husky/blob/master/CHANGELOG.md#&#8203;100-rc2)

* Upgrade `run-node` dependency

---

</details>

<details>
<summary>Commits</summary>

#### v1.0.0-rc.2
-   [`2619144`](https://github.com/typicode/husky/commit/2619144a8306c64393b04dfbf02743a9b513e6ac) Update docs.md
-   [`57dc135`](https://github.com/typicode/husky/commit/57dc13561cc9152d79f5820c9d178267e790dfbb) Add typing
-   [`a3d44f2`](https://github.com/typicode/husky/commit/a3d44f233d74e61aa9ad5cce5c1fa7b2a1ea628d) Update package.json
-   [`a1e0a0d`](https://github.com/typicode/husky/commit/a1e0a0d049bea5c9fa84eb66406e8e08cbe34d5d) Merge branch &#x27;dev&#x27; of https://github.com/typicode/husky into dev
-   [`3cb9d23`](https://github.com/typicode/husky/commit/3cb9d23dd6cf3eebea95bb09c0a2c1c3f022e1b3) upgrade: run-node to 1.0.0 (#&#8203;275)
-   [`de7345b`](https://github.com/typicode/husky/commit/de7345b88497f62f1eff4e9e462568f46c55e011) Update package-lock.json
-   [`d5dcde7`](https://github.com/typicode/husky/commit/d5dcde7014162af5103cc8016198f0b94a4d9ad5) Update CHANGELOG.md
-   [`58be370`](https://github.com/typicode/husky/commit/58be370e343ca244470fe8397ca4a87622585b06) Debug output
-   [`39e8813`](https://github.com/typicode/husky/commit/39e881353def8ee601373cfaa0794965f64dc0ca) Bump
-   [`6458f51`](https://github.com/typicode/husky/commit/6458f5109074287214d6bf6158a2aa59d9aa6bb4) Update snapshots

</details>

---

This PR has been generated by [Renovate Bot](https://renovateapp.com).

### CODE REVIEW

**Comment by juliangieseke** [comment]
why are we using a `-rc` build? 🤔

**Comment by nLight** [comment]
@juliangieseke we gotta create the config file so that we skip them

**Comment by juliangieseke** [comment]
@nLight how to? wasnt able to find it in the config manual 🤔

**Comment by DanielMSchmidt** [comment]
@juliangieseke @nLight I decided to go with a pre-release because it looked stable and I like the new version a lot more than the old one. I made the call here not renovate

**Pull request merged**
